### ISSUE TITLE
Angular 14

### ISSUE THREAD

**Issue by bevrard** [guzmanoj/ngx-onetrust#3]
Hello,

Do you plan to migrate to Angular 14? or it will not be supported?

Kind regards

**Comment by wall-street-dev** [comment]
Hi @bevrard  thank you for the issue. V14 is planned, absolutely.
The main issue right now is that I cannot test.
I will publish an alpha version, maybe you could give it a try before actually making it public.
Does it make any sense?
As far as I can tell, the OneTrust API remains the same, so everything  should continue working as expected.

**Comment by bevrard** [comment]
I'm also "blocked" in version 13 for now, it's just to foresee.
Thanks for your feedback, I'm closing the ticket.
